---
#- name: Add index.html
#  ansible.builtin.lineinfile:
#   path: /var/www/html/index.html
#   line: Hello, Welcome to ansible roles
#   create: yes
#  notify:
# - restart apache
- name: index.html using jinja2
  template:
    src: first.j2
    dest: /var/www/html/index.html
    mode: 0775